# pandas_cheatsheet

## overview

| R           | Python        |
|-------------|---------------|
| head(df, n) | df.head(n)    |
| dim(df)     | df.shape      |
| str(df)     | df.info()     |
| summary(df) | df.describe() |

## 取colnames, rownames, values

| R            | Python     |
|--------------|------------|
| colnames(df) | df.columns |
| rownames(df) | df.index   |
|              | df.values  |

## .loc & .iloc

+-------------------------------------------------------------+-----------------------------------------------+
| 說明                                                        | pandas                                        |
+=============================================================+===============================================+
| `取[某列,某行]，得value (此時不再是df type)`                | `df.loc["列名1","行名2"]`                     |
+-------------------------------------------------------------+-----------------------------------------------+
| 若要維持df type，要加中括號                                 | `df.loc[["列名1"],["行名2"]]`                 |
+-------------------------------------------------------------+-----------------------------------------------+
| 取多個列，多個行                                            | `df.loc[["列名1","列名2"],["行名2","行名2"]]` |
+-------------------------------------------------------------+-----------------------------------------------+
| 若要取多個列就好，行我全要                                  |     錯誤: df.loc[[列名1, 列名2], :]           |
|                                                             |                                               |
|                                                             |     正確: df.loc[[列名1, 列名2]]              |
+-------------------------------------------------------------+-----------------------------------------------+
| 若要取多個行就好，列我全要                                  | `df.loc[:, [行名1, 行名2]]`                   |
+-------------------------------------------------------------+-----------------------------------------------+
| 取連續的列                                                  |     錯誤: df.loc[["列名2":"列名7"]]           |
|                                                             |                                               |
|                                                             |     正確: df.loc["列名2":"列名7"]             |
+-------------------------------------------------------------+-----------------------------------------------+
| 排序後，取連續的行                                          |     錯誤: df.loc[:, ["行名2":"行名7"]]        |
|                                                             |                                               |
|                                                             |     正確: df.loc[:, "行名2":"行名7"]          |
+-------------------------------------------------------------+-----------------------------------------------+
| .iloc就是把列名全改成列數(0開始), 行名全改成行數(0開始)就好 |     df.iloc[0,2] # 返回value                  |
|                                                             |     df.iloc[[0],[2]] # 返回df type            |
|                                                             |     df.iloc[[0,2], [0,1]] #多列多行           |
|                                                             |     df.iloc[[0,2]] # 多列                     |
|                                                             |     df.iloc[:, [0,1]] # 多行                  |
+-------------------------------------------------------------+-----------------------------------------------+

## indexing (another filter & arrange method)

-   簡單講，就是把某個column，設成row index，那接下來就可以用`.loc[[列名1, 列名2]]` 來進行filter

-   更特別的是，row index可以接受multi-column，所以當我們想篩選出類似實驗設計的多種treatment時(例如"A=1且B=2" 或 "A=2且B=3")，特別適合用這種方式來篩選。

+---------------------------------+---------------------------------------+
| 說明                            |                                       |
+---------------------------------+---------------------------------------+
| 將欄位 a 設成 index             | df_ind = df.set_index("a")            |
|                                 |                                       |
| 將 index 回覆成欄位             | df_orig = df_ind.reset_index()        |
+---------------------------------+---------------------------------------+
|     df %>%                      |     df \                              |
|       filter(a == 1)            |       .set_index("a") \               |
|                                 |       .loc["1"] \                     |
|                                 |       .reset_index()                  |
+---------------------------------+---------------------------------------+
|     df %>%                      |     df \                              |
|       filter(a %in% c("1","2")) |       .set_index("a") \               |
|                                 |       .loc[["1","2"]] \               |
|                                 |       .reset_index()                  |
+---------------------------------+---------------------------------------+
|     df %>%                      |     df \                              |
|       filter(                   |       .set_index("a","b") \           |
|         (a == 1 & b == 2) |     |       .loc[(1,2), (3,5)] \            |
|         (a == 3 & b == 5)       |       .reset_index()                  |
|       )                         |                                       |
+---------------------------------+---------------------------------------+
|     df %>%                      |     df \                              |
|       arrange(a)                |       .set_index("a") \               |
|                                 |       .sort_index() \                 |
|                                 |       .reset_index()                  |
+---------------------------------+---------------------------------------+
|     df %>%                      |     df \                              |
|       arrange(desc(a))          |       .set_index("a") \               |
|                                 |       .sort_index() \                 |
|                                 |       .reset_index(ascending = False) |
+---------------------------------+---------------------------------------+
|     df %>%                      |     df \                              |
|       arrange(a, desc(b))       |       .set_index("a", "b") \          |
|                                 |       .sort_index(                    |
|                                 |         level = ["a","b"],            |
|                                 |         ascending = [True, False]     |
|                                 |       )                               |
+---------------------------------+---------------------------------------+
|                                 |                                       |
+---------------------------------+---------------------------------------+
|                                 |                                       |
+---------------------------------+---------------------------------------+

## select/filter/arrange/mutate

### select

+----------------------------------------+--------------------------------------------------------------------------+
| dplyr                                  | Pandas                                                                   |
+========================================+==========================================================================+
|     df %>%                             |     df["col1"] # series                                                  |
|       select(col1)                     |     df[["col1"]] # df                                                    |
+----------------------------------------+--------------------------------------------------------------------------+
|     df %>%                             |     df[["col1", "col2"]]                                                 |
|       select(col1, col2)               |                                                                          |
+----------------------------------------+--------------------------------------------------------------------------+
|     df %>%                             |     df.loc[:, "col1":"col3"]                                             |
|       select(col1:col3)                |                                                                          |
+----------------------------------------+--------------------------------------------------------------------------+
|     df[,1:3]                           |     df.iloc[:, 0:3] # from:stop                                          |
+----------------------------------------+--------------------------------------------------------------------------+
|     n = ncol(df)                       |     df.iloc[:, -3:]                                                      |
|     df[, (n-3):n]                      |                                                                          |
+----------------------------------------+--------------------------------------------------------------------------+
|     df %>%                             |     df \                                                                 |
|       select(where(is.numeric))        |       .select_dtypes(                                                    |
|                                        |         include = ["int","float"]                                        |
|                                        |       )                                                                  |
+----------------------------------------+--------------------------------------------------------------------------+
|     df %>%                             |     df \                                                                 |
|       select(where(!is.numeric))       |       .select_dtypes(                                                    |
|                                        |         exclude = ["int","float"]                                        |
|                                        |       )                                                                  |
+----------------------------------------+--------------------------------------------------------------------------+
|     df %>%                             |     df.drop(["col1", "col2"], axis =1)                                   |
|       select(-c(col1, col2))           |                                                                          |
+----------------------------------------+--------------------------------------------------------------------------+
|     df %>%                             | QQ                                                                       |
|       select(-(col1:col3))             |                                                                          |
+----------------------------------------+--------------------------------------------------------------------------+
|     df %>%                             |     my_list = df.columns.tolist()                                        |
|       select(col3, everything())       |     my_list.remove("col3")                                               |
|                                        |     new_order = ["col3", *my_list]                                       |
|                                        |     df[new_order]                                                        |
+----------------------------------------+--------------------------------------------------------------------------+
|     df %>%                             |     my_list = df.columns.tolist()                                        |
|       select(col3, col5, everything()) |     front = ["col3", "col5"]                                             |
|                                        |     end = [col for col in my_list if col not in front]                   |
|                                        |     new_order = [*front, *end]                                           |
|                                        |     df[new_order]                                                        |
|                                        |                                                                          |
|                                        | ------------------------------------------------------------------------ |
|                                        |                                                                          |
|                                        |     front = ["col3", "col5"]                                             |
|                                        |     df1 = df[front]                                                      |
|                                        |     df2 = df.drop(front, axis = 1)                                       |
|                                        |     pd.concat([df1, df2], axis = 1)                                      |
+----------------------------------------+--------------------------------------------------------------------------+

### filter

+-------------------------------------------------+---------------------------------------------------+
| dplyr                                           | Pandas                                            |
+=================================================+===================================================+
|     df %>%                                      |     df[df["col1"]==1]                             |
|       filter(col1 == 1)                         |     df.query("col1 == 1")                         |
+-------------------------------------------------+---------------------------------------------------+
|     df %>%                                      |     df[df["col1"] > pd.datetime("2021-01-01")]    |
|       filter(col1 > ymd("2021-01-01"))          |     df.query("col1 > @pd.datetime("2021-01-01")") |
+-------------------------------------------------+---------------------------------------------------+
|     df %>%                                      |     df[df["col1"].isin(["brown","black"])]        |
|       filter(col1 %in% c("brown", "black"))     |                                                   |
+-------------------------------------------------+---------------------------------------------------+
|     df %>%                                      |     df[-df["col1"].isin(["brown","black"])        |
|       filter(! (col1 %in% c("brown", "black"))) |     # python 的 - 就是R的 !                       |
+-------------------------------------------------+---------------------------------------------------+
|     df %>%                                      |     df[df["col1"]==1 & df["col2"]==1]             |
|       filter(col1 == 1, col2 == 1)              |                                                   |
|                                                 |     df.query("col1 == 1 & col2 ==1")              |
+-------------------------------------------------+---------------------------------------------------+
| head(df)                                        | df.head()                                         |
+-------------------------------------------------+---------------------------------------------------+
| tail(df)                                        | df.tail()                                         |
+-------------------------------------------------+---------------------------------------------------+
|     df[1:5,]                                    |     df.iloc[0:5,:]                                |
+-------------------------------------------------+---------------------------------------------------+
|     df[c(1,3,4), c(2,5)]                        |     df.iloc[[0,2,3], [1,4]]                       |
+-------------------------------------------------+---------------------------------------------------+

### arrange

+---------------------------------+-----------------------------------------------+
| dplyr                           | Pandas                                        |
+=================================+===============================================+
|     df %>%                      |     df \                                      |
|       arrange(col1)             |       .sort_values("col1")                    |
+---------------------------------+-----------------------------------------------+
|     df %>%                      |     df \                                      |
|       arrange(desc(col1))       |       .sort_values("col1", ascending = False) |
+---------------------------------+-----------------------------------------------+
|     df %>%                      |     df \                                      |
|       arrange(col1, col2)       |       .sort_values(["col1", "col2"])          |
+---------------------------------+-----------------------------------------------+
|     df %>%                      |     df \                                      |
|       arrange(col1, desc(col2)) |       .sort_values(                           |
|                                 |         ["col1","col2"],                      |
|                                 |         ascending = [True, False]             |
|                                 |       )                                       |
+---------------------------------+-----------------------------------------------+

### mutate and rename

+---------------------------------+-------------------------------------------------------------+
| dplyr                           | Pandas                                                      |
+=================================+=============================================================+
|     df %>%                      |     df['c'] = df['a'] - df['b']                             |
|       mutate(c = a - b)         |     df.assign(c = df["a"]-df["b"])                          |
+---------------------------------+-------------------------------------------------------------+
|     df %>%                      |     df.query("a == 'a1'") \                                 |
|       filter(a == "a1") %>%     |       .assign(c = lambda x: x['a']-x['b'])                  |
|       mutate(c = a - b)         |     # x 是 current data 的代名詞，因為這邊不是要用df['a']了 |
+---------------------------------+-------------------------------------------------------------+
|     df %>%                      |     df \                                                    |
|       rename(col_new = col_old) |       .rename(                                              |
|                                 |         columns = {'col_old':'col_new'}                     |
|                                 |       )                                                     |
+---------------------------------+-------------------------------------------------------------+

## group_by & summarise

### 對 vector/series 做 summarise (結果是數值)

| R                | Pandas                |
|------------------|-----------------------|
| mean(df\$col1)   | `df["col1"].mean()`   |
| median(df\$col1) | `df["col1"].median()` |
| mode(df\$col1)   | `df["col1"].mode()`   |
| min(df\$col1)    | `df["col1"].min()`    |
| max(df\$col1)    | `df["col1"].max()`    |
| var(df\$col1)    | `df["col1"].var()`    |
| sd(df\$col1)     | `df.["col1"].std()`   |
| sum(df\$col1)    | `df.["col1"].sum()`   |

### 對 dataframe 做 summarise (結果仍是df)

+-----------------------------------------------------------+------------------------------------------+
| dplyr                                                     | Pandas                                   |
+===========================================================+==========================================+
|     df %>%                                                |     # series                             |
|       summarise(mean_col1 = mean(col1)) #仍是 table       |     df[['col1']].mean()                  |
|                                                           |                                          |
|                                                           |     # dataframe                          |
|                                                           |     df[['col1']].mean()                  |
|                                                           |                                          |
|                                                           |     df[['col1']].mean() \                |
|                                                           |       .to_frame(name = "mean_col1")      |
|                                                           |                                          |
|                                                           |     df[['col1']].agg(np.mean) \          |
|                                                           |       .to_frame(name = "mean_col1")      |
|                                                           |                                          |
|                                                           |     df \                                 |
|                                                           |       .agg({'col1': np.mean}) \          |
|                                                           |       .to_frame(name = "mean_col1")      |
+-----------------------------------------------------------+------------------------------------------+
|     df %>%                                                |     df \                                 |
|       summarise(                                          |       .agg(                              |
|         mean_col1 = mean(col1),                           |         {                                |
|         med_col1 = median(col1)                           |           'col1': np.mean,               |
|       )                                                   |           'col2': np.median              |
|                                                           |         }                                |
|                                                           |       ) #沒辦法命名了，格式是直的        |
+-----------------------------------------------------------+------------------------------------------+
|     df %>%                                                |     df \                                 |
|       summarise(                                          |       .agg({                             |
|         mean(col1),                                       |         'col1': np.mean,                 |
|         mean(col2),                                       |         'col2': [np.mean, np.median]     |
|         median(col2)                                      |       }) # 格式變成 cross                |
|       )                                                   |                                          |
+-----------------------------------------------------------+------------------------------------------+
|     range2 = function(x){                                 |     def range2(x):                       |
|       max(x) - min(x)                                     |       return x.max() - x.min()           |
|     }                                                     |                                          |
|                                                           |     df.agg([np.mean, np.median, range2]) |
|     summarise(df, mean(col1), median(col2), range2(col1)) |                                          |
+-----------------------------------------------------------+------------------------------------------+

### 對整張 table 的 各column 做 summarise

+-------------------------------------+------------------------------------+
| R                                   | Python                             |
+=====================================+====================================+
| colSum(df) \# length = p 的 vector  | df.sum() \# px1 series             |
|                                     |                                    |
| summarise_all(df, sum) \# 1xp table | df.agg(np.sum) \# px1 series       |
|                                     |                                    |
|                                     | df.sum().to_frame() \# px1 table   |
|                                     |                                    |
|                                     | df.sum().to_frame().T \# 1xp table |
+-------------------------------------+------------------------------------+
| QQ                                  |     df.agg([np.sum, np.median])    |
+-------------------------------------+------------------------------------+
|     df %>%                          |     df[['col1', 'col2']] \         |
|       summarise(                    |       .sum() # 2x1 series          |
|         across(c(col1, col2), sum)  |                                    |
|       )                             |                                    |
+-------------------------------------+------------------------------------+
|                                     |                                    |
+-------------------------------------+------------------------------------+

### group_by + summarise

+--------------------------------------------------------------+-------------------------------------------------------------------------+
| dplyr                                                        | Pandas                                                                  |
+==============================================================+=========================================================================+
| gdf = group_by(df, col1)                                     | gdf = df.groupby("col1") #col1從 variable 變成 rowname(i.e. index)      |
+--------------------------------------------------------------+-------------------------------------------------------------------------+
| gdf2 = group_by(df, col1, col2)                              | gdf2 = df.groupby(\["col1", "col2"\]) \# col1, col2 現在都是 index      |
+--------------------------------------------------------------+-------------------------------------------------------------------------+
|     df %>%                                                   |     df.groupby("col1")["col2"].mean()                                   |
|       group_by(col1) %>%                                     |                                                                         |
|       summarise(mean(col2))                                  |     df.groupby("col1")["col2"].agg(np.mean)                             |
|                                                              |                                                                         |
|                                                              |     df[["col1","col2"]].groupby("col1").agg(np.mean)                    |
|                                                              |                                                                         |
|                                                              |     df.groupby("col1").agg({"col2": np.mean})                           |
+--------------------------------------------------------------+-------------------------------------------------------------------------+
|     df %>%                                                   |     df.groupby("col1")["col2"].agg([np.mean, np.median])                |
|       group_by(col1) %>%                                     |                                                                         |
|       summarise(mean(col2), median(col2))                    |     df.groupby("col1").agg({"col2": [np.mean, np.median]})              |
+--------------------------------------------------------------+-------------------------------------------------------------------------+
|     df %>%                                                   |     df.groupby(["col1","col2"])["col3","col4"].agg([np.mean, np.min)    |
|       group_by(col1, col2) %>%                               |                                                                         |
|       summarise(mean(col3),mean(col4), min(col3), min(col4)) |                                                                         |
+--------------------------------------------------------------+-------------------------------------------------------------------------+
|     df %>%                                                   |     df.groupby(["col1","col2"]).agg({'col3': 'mean', 'col4', 'median'}) |
|       group_by(col1, col2) %>%                               |                                                                         |
|       summarise(mean(col3), median(col4))                    |                                                                         |
+--------------------------------------------------------------+-------------------------------------------------------------------------+

### group_by + mutate

+---------------------------------------+--------------------------------------------------+
| dplyr                                 | pandas                                           |
+=======================================+==================================================+
|     df %>%                            | QQ                                               |
|       group_by(a) %>%                 |                                                  |
|       mutate(b = c + d)               |                                                  |
+---------------------------------------+--------------------------------------------------+
|     df %>%                            | QQ                                               |
|       group_by(a) %>%                 |                                                  |
|       mutate(b = (b - mean(b))/sd(b)) |                                                  |
+---------------------------------------+--------------------------------------------------+
|                                       |     # 對 a 分組，normalize所有column             |
|                                       |     df \                                         |
|                                       |       .groupby('a') \                            |
|                                       |       .apply(lambda x: (x - x.mean())/x.std()) \ |
|                                       |       .reset_index()                             |
+---------------------------------------+--------------------------------------------------+

### group_by + filter

+-----------------------+----------------------------------------+
| dplyr                 | pandas                                 |
+=======================+========================================+
|     df %>%            |     df \                               |
|       group_by(a) %>% |         .groupby("a") \                |
|       filter(b > 50)  |         .apply(lambda x: x[x["b"]>50]) |
+-----------------------+----------------------------------------+
|                       |                                        |
+-----------------------+----------------------------------------+
|                       |                                        |
+-----------------------+----------------------------------------+

### group_by + arrange

+-----------------------+--------+
| dplyr                 | pandas |
+=======================+========+
|     df %>%            | QQ     |
|       group_by(a) %>% |        |
|       arrange(b)      |        |
+-----------------------+--------+
|                       |        |
+-----------------------+--------+
|                       |        |
+-----------------------+--------+

### group_by + slice

+-----------------------+------------------------------------+
| dplyr                 | pandas                             |
+-----------------------+------------------------------------+
|     df %>%            |     df \                           |
|       group_by(a) %>% |       .groupby(a) \                |
|       slice(1:5)      |       .head(5)                     |
|                       |                                    |
|                       |     df \                           |
|                       |       .groupby(a) \                |
|                       |       .apply(lambda x: x.iloc[:5]) |
+-----------------------+------------------------------------+
|                       |                                    |
+-----------------------+------------------------------------+

## others

### distinct & unique

+----------------------------+--------------------------------------------+
| dplyr                      | Pandas                                     |
+============================+============================================+
|     df %>%                 |     # series                               |
|       distinct(col1)       |     df["col1"].drop_duplicates()           |
|                            |     # dataframe                            |
|                            |     df[["col1"]].drop_duplicates()         |
+----------------------------+--------------------------------------------+
|     df %>%                 |     df[["col1", "col2"]].drop_duplicates() |
|       distinct(col1, col2) |                                            |
+----------------------------+--------------------------------------------+
| unique(df\$col1)           |     df['col1'].unique() # ndarray          |
+----------------------------+--------------------------------------------+
|                            | df.nunique() \# 每個欄位的 unique 數量     |
+----------------------------+--------------------------------------------+

### slice

| dplyr           | Pandas           |
|-----------------|------------------|
| slice(df, 1:10) | `df.iloc[0:9,:]` |
|                 |                  |

### count

| dplyr                 | Pandas                                      |
|-----------------------|---------------------------------------------|
| count(df, col1)       | `df["col1"].value_counts()`                 |
| count(df, col1, col2) | `df[["col1","col2"]].value_counts()`        |
|                       | `df["col1"].value_counts(normalize = True)` |
|                       |                                             |

### largest/smallest

+---+-------------------------------+
| R | Python                        |
+===+===============================+
|   |     df.nlargest(              |
|   |       n = 5,                  |
|   |       columns = 'total_price' |
|   |     )                         |
+---+-------------------------------+
|   |     df.nsmallest(             |
|   |       n = 5,                  |
|   |       columns = 'total_price' |
|   |     )                         |
+---+-------------------------------+
|   |                               |
+---+-------------------------------+

### random sampling rows

| R   | Python                                    |
|-----|-------------------------------------------|
|     | df.sample(n = 10, random_state = 17)      |
|     | df.sample(frac = 0.10, random_state = 17) |
|     |                                           |

### categorization

+---------+-----------------------------------------------------------------------+
| R       | Python                                                                |
+=========+=======================================================================+
|         |     pd.cut(df['price'], bins = 3)                                     |
|         |                                                                       |
|         |     pd.cut(df['price'], bins = 3, labels = ['low', 'medium', 'high']) |
+---------+-----------------------------------------------------------------------+
|         |     pd.qcut(df['price'], q = [0, 0.25, 0.5, 0.75, 1])                 |
|         |                                                                       |
|         |     pd.qcut(df['price'], q = 4) #4等分                                |
+---------+-----------------------------------------------------------------------+
|         |                                                                       |
+---------+-----------------------------------------------------------------------+

### missing data

| R                           | Python                                |
|-----------------------------|---------------------------------------|
| is.na(df)                   | df.isna() \# 整張table各cell是否為 NA |
| df %>% is.na() %>% colSum() | df.isna().sum() \# 各欄位 missing 數  |
|                             |                                       |

## pivot table

-   pandas有個dplyr沒有的優點，就是他可以做excel的樞紐分析表\
-   最簡單的例子，就是你可以指定table的row是性別，col是年級，然後cell是去算該性別該年級下的平均成績之類的

+--------------------+-----------------------------------------------+
| dplyr無, Excel樞紐 | pandas                                        |
+====================+===============================================+
|                    |     df.pivot_table(                           |
|                    |       index = cat_col1, #row                  |
|                    |       columns = cat_col2, #col                |
|                    |       values = con_col, #cell要by誰做計算     |
|                    |       aggfunc = np.mean, #計算用的function    |
|                    |       margins = True #是否要算overall row/col |
|                    |     )                                         |
+--------------------+-----------------------------------------------+

## 字串相關的處理

+---------------------------------------+-------------------------------------------------+
| dplyr + stringr                       | pandas                                          |
+=======================================+=================================================+
|     # 篩選出 a 欄位有 "ist" 字串的列  |     # 篩選出 a 欄位有 "ist" 字串的列            |
|     df %>%                            |     df[df['a'].str.lower().str.contains("ist")] |
|       mutate(a = str_to_lower(a)) %>% |                                                 |
|       filter(str_detect(a, "ist"))    |                                                 |
+---------------------------------------+-------------------------------------------------+
|                                       |                                                 |
+---------------------------------------+-------------------------------------------------+
|                                       |                                                 |
+---------------------------------------+-------------------------------------------------+
|                                       |                                                 |
+---------------------------------------+-------------------------------------------------+
|                                       |                                                 |
+---------------------------------------+-------------------------------------------------+

## 離散化的處理

+--------------+----------------------------------------------------------------------------------------------------------+
| dplyr + base | pandas                                                                                                   |
+==============+==========================================================================================================+
|              |     # 將數值變數a，切成三等分                                                                            |
|              |     df.assign(a_cat = pd.cut(df['price'], bins = 3, labels = ['low', 'medium','high'))                   |
+--------------+----------------------------------------------------------------------------------------------------------+
|              |     # 將數值變數a，用我自定義的quantile，切成三等分                                                      |
|              |     df.assign(a_cat = pd.qcut(df['price'], q = q=[0, 0.33, 0.66, 1]), labels = ['low', 'medium','high')) |
+--------------+----------------------------------------------------------------------------------------------------------+
|              |                                                                                                          |
+--------------+----------------------------------------------------------------------------------------------------------+

## Combine variables

+-----------------------------------------------------------+---------------------------------------------------+
| dplyr                                                     | pandas                                            |
+===========================================================+===================================================+
| bind_cols(x, y)                                           | pd.concat(df1, df2, axis = 1)                     |
+-----------------------------------------------------------+---------------------------------------------------+
| inner_join(x, y)                                          | x.merge(y, on = "col1")                           |
+-----------------------------------------------------------+---------------------------------------------------+
| full_join(x, y)                                           | x.merge(y, on = "col1", how = "outer")            |
+-----------------------------------------------------------+---------------------------------------------------+
| left_join(x, y)                                           | x.merge(y, on = "col1", how = "left")             |
+-----------------------------------------------------------+---------------------------------------------------+
| right_join(x, y)                                          | x.merge(y, on = "col1", how = "right")            |
+-----------------------------------------------------------+---------------------------------------------------+
| left_join(x, y, by = c("col1", "col2")                    | x.merge(y, how = "left", on = \["col1", "col2"\]) |
+-----------------------------------------------------------+---------------------------------------------------+
|     left_join(x, y,                                       |     x.merge(y,                                    |
|             by = c("col1_x" = "col1_y, "col2_x"="col2_y), |             how = "left",                         |
|             suffix = c("x", "y"))                         |             left_on = ["col1_x","col2_x",         |
|                                                           |             right_on = ["col1_y","col2_y"],       |
|                                                           |             suffixes = ["_x","_y"])               |
+-----------------------------------------------------------+---------------------------------------------------+
|                                                           |                                                   |
+-----------------------------------------------------------+---------------------------------------------------+

## Combine cases

| R                   | Python                        |
|---------------------|-------------------------------|
| bind_rows(df1, df2) | pd.concat(df1, df2, axis = 0) |
|                     |                               |
|                     |                               |
